# Generated by Django 2.0.7 on 2019-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repairpiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Repairtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieceID', models.IntegerField()),
                ('typename', models.CharField(max_length=25)),
            ],
        ),
    ]
