# Generated by Django 2.1.7 on 2019-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairpiece',
            name='types',
            field=models.ManyToManyField(to='piece.Repairtype'),
        ),
        migrations.AlterField(
            model_name='repairtype',
            name='typename',
            field=models.CharField(max_length=2),
        ),
    ]
