# Generated by Django 2.1.7 on 2019-03-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0003_remove_repairtype_pieceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairtype',
            name='typename',
            field=models.CharField(max_length=25),
        ),
    ]
